os:
  - linux
  - osx

language: cpp

env:
  matrix:
  - TRAVIS_NODE_VERSION="8"
  - TRAVIS_NODE_VERSION="10"
  - TRAVIS_NODE_VERSION="12"
  - TRAVIS_NODE_VERSION="14"
  - TRAVIS_NODE_VERSION="15"

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - $CXX --version
  - travis_retry npm install

script: travis_retry npm test
