name: build

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        virtual-environment: ['ubuntu-latest', 'macos-13', 'windows-2019']
        node: [12, 14, 16, 18, 20, 22]

    runs-on: ${{ matrix.virtual-environment }}

    steps:
    - name: Configure git (Windows specific)
      if: matrix.virtual-environment == 'windows-2019'
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v4
      uses: actions/setup-python@v5
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies and build
      run: npm install

    - name: Run linter
      run: node node_modules/eslint/bin/eslint .

    - name: Run test suite
      run: node node_modules/mocha/bin/mocha tests
