name: build

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        virtual-environment: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node: [8, 10, 12, 14, 16, 17]

    runs-on: ${{ matrix.virtual-environment }}

    steps:
    - name: Configure git (Windows specific)
      if: matrix.virtual-environment == 'windows-latest'
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v2

    - name: Add msbuild to PATH (Windows specific)
      if: matrix.virtual-environment == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies and build
      run: npm install

    - name: Run linter
      run: node node_modules/eslint/bin/eslint .

    - name: Run test suite
      run: node node_modules/mocha/bin/mocha tests
