name: build

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        virtual-environment: ['ubuntu-latest', 'macos-latest', 'windows-2019']
        node: [10, 12, 14, 16, 18, 19]
        include:
          - node: 8
            virtual-environment: 'ubuntu-20.04'
          - node: 8
            virtual-environment: 'macos-11'
          - node: 8
            virtual-environment: 'windows-2019'

    runs-on: ${{ matrix.virtual-environment }}

    steps:
    - name: Configure git (Windows specific)
      if: matrix.virtual-environment == 'windows-2019'
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies and build
      run: npm install

    - name: Run linter
      run: node node_modules/eslint/bin/eslint .

    - name: Run test suite
      run: node node_modules/mocha/bin/mocha tests
